stages: # List of stages for jobs, and their order of execution
  - build
  - test

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ./build.sh
  tags: [xavier]

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - ./run_gpu.sh
    - ./run_cpu.sh
  tags: [xavier]
